In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


In [7]:
df=pd.read_csv("/home/sachchida/gitrepo/ml/data/hate-speech/labeled_data.csv")
df.head()

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2   
1           1      3            0                   3        0      1   
2           2      3            0                   3        0      1   
3           3      3            0                   2        1      1   
4           4      6            0                   6        0      1   

                                               tweet  
0  !!! RT @mayasolovely: As a woman you shouldn't...  
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [8]:
import re
def clean_text(text):
    # remove HTML
    text = re.sub(r'<.*?>', '', text)
    # replace URLs
    text = re.sub(r'http\S+|www\S+', ' URL ', text)
    # replace user mentions (handles @name and @name:)
    text = re.sub(r'@\w+:?', ' USER ', text)
    # keep hashtag text
    text = re.sub(r'#(\w+)', r'\1', text)
    # lowercase
    text = text.lower()
    # remove non-alphabetic characters
    text = re.sub(r'[^a-z\s]', '', text)
    # normalize spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text
import re
def clean_text_with_caps(text):
    text = re.sub(r'<.*?>', '', text)   # HTML
    text = re.sub(r'http\S+|www\S+', ' <URL> ', text)
    text = re.sub(r'@\w+', ' <USER> ', text)
    text = re.sub(r'#(\w+)', r'\1', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # keep caps
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [9]:
df['tweet_cleaned']=df['tweet'].apply(clean_text)
df['tweet_cleaned_caps']=df['tweet'].apply(clean_text_with_caps)

In [136]:
df.head()

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2   
1           1      3            0                   3        0      1   
2           2      3            0                   3        0      1   
3           3      3            0                   2        1      1   
4           4      6            0                   6        0      1   

                                               tweet  \
0  !!! RT @mayasolovely: As a woman you shouldn't...   
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...   
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...   
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...   
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...   

                                       tweet_cleaned  \
0  rt user as a woman you shouldnt complain about...   
1  rt user boy dats coldtyga dwn bad for cuffin d...   
2  rt user dawg rt user you ever fuck a bitch and...   
3                rt user user she look like a tranny   
4  rt user the shit you hear about me might be tr...   

                                  tweet_cleaned_caps  
0  RT USER As a woman you shouldnt complain about...  
1  RT USER boy dats coldtyga dwn bad for cuffin d...  
2  RT USER Dawg RT USER You ever fuck a bitch and...  
3                RT USER USER she look like a tranny  
4  RT USER The shit you hear about me might be tr...

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

word_tfidf=TfidfVectorizer(
    analyzer="word",
    ngram_range=(1,2),
    stop_words='english',
    min_df=3, ## ignore terms (words) that appear in fewer than 3 different documents
    max_df=0.9 ## ignore terms that appear in more than 90% of the documents
)
char_tfidf=TfidfVectorizer(
    analyzer='char',
    ngram_range=(3,5),
)

In [138]:
df=df.drop(['Unnamed: 0','count','hate_speech','offensive_language','neither'],axis=1)
df.head()

class                                              tweet  \
0      2  !!! RT @mayasolovely: As a woman you shouldn't...   
1      1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...   
2      1  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...   
3      1  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...   
4      1  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...   

                                       tweet_cleaned  \
0  rt user as a woman you shouldnt complain about...   
1  rt user boy dats coldtyga dwn bad for cuffin d...   
2  rt user dawg rt user you ever fuck a bitch and...   
3                rt user user she look like a tranny   
4  rt user the shit you hear about me might be tr...   

                                  tweet_cleaned_caps  
0  RT USER As a woman you shouldnt complain about...  
1  RT USER boy dats coldtyga dwn bad for cuffin d...  
2  RT USER Dawg RT USER You ever fuck a bitch and...  
3                RT USER USER she look like a tranny  
4  RT USER The shit you hear about me might be tr...

In [11]:
from sklearn.model_selection import train_test_split
X=df['tweet_cleaned']
y=df['class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


In [12]:
X_train_tfidf_word=word_tfidf.fit_transform(X_train)
X_test_tfidf_word=word_tfidf.transform(X_test)

In [13]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    n_jobs=-1
)
model.fit(X_train_tfidf_word,y_train)

/home/sachchida/anaconda3/envs/agentic-ai/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)


LogisticRegression(class_weight='balanced', max_iter=1000, n_jobs=-1)

In [142]:
from sklearn.metrics import classification_report,confusion_matrix

y_pred=model.predict(X_test_tfidf_word)

In [143]:
from sklearn.metrics import classification_report,f1_score,confusion_matrix

In [144]:
print(f"classification_report",classification_report(y_test,y_pred))
print(f"Confusion Matrix ",confusion_matrix(y_test,y_pred))
print(f"Macro Average F1 Score ",f1_score(y_test,y_pred,average="macro"))
print(f"Weighted Average F1 Score ",f1_score(y_test,y_pred,average="weighted"))

classification_report               precision    recall  f1-score   support

           0       0.32      0.60      0.42       290
           1       0.97      0.86      0.91      3832
           2       0.76      0.92      0.83       835

    accuracy                           0.86      4957
   macro avg       0.68      0.79      0.72      4957
weighted avg       0.90      0.86      0.87      4957

Confusion Matrix  [[ 173   76   41]
 [ 330 3300  202]
 [  31   33  771]]
Macro Average F1 Score  0.7217811776923838
Weighted Average F1 Score  0.8696609400993828


In [145]:
from sklearn.svm import LinearSVC
svm=LinearSVC()
svm.fit(X_train_tfidf_word,y_train)
y_pred_svm=svm.predict(X_test_tfidf_word)

In [146]:
print(f"classification_report",classification_report(y_test,y_pred_svm))
print(f"Confusion Matrix ",confusion_matrix(y_test,y_pred_svm))
print(f"Macro Average F1 Score ",f1_score(y_test,y_pred_svm,average="macro"))
print(f"Weighted Average F1 Score ",f1_score(y_test,y_pred_svm,average="weighted"))

classification_report               precision    recall  f1-score   support

           0       0.45      0.25      0.32       290
           1       0.92      0.95      0.94      3832
           2       0.83      0.84      0.84       835

    accuracy                           0.89      4957
   macro avg       0.73      0.68      0.70      4957
weighted avg       0.88      0.89      0.88      4957

Confusion Matrix  [[  73  188   29]
 [  74 3642  116]
 [  16  114  705]]
Macro Average F1 Score  0.6986064843422541
Weighted Average F1 Score  0.8839485634757537


In [148]:
from sklearn.svm import SVC
svc_rbf=SVC(kernel='rbf', gamma='scale')
svc_rbf.fit(X_train_tfidf_word,y_train)
y_pred_svc_rbf=svc_rbf.predict(X_test_tfidf_word)

In [ ]:
print(f"classification_report",classification_report(y_test,y_pred_svm))
print(f"Confusion Matrix ",confusion_matrix(y_test,y_pred_svm))
print(f"Macro Average F1 Score ",f1_score(y_test,y_pred_svm,average="macro"))
print(f"Weighted Average F1 Score ",f1_score(y_test,y_pred_svm,average="weighted"))

classification_report               precision    recall  f1-score   support

           0       0.45      0.25      0.32       290
           1       0.92      0.95      0.94      3832
           2       0.83      0.84      0.84       835

    accuracy                           0.89      4957
   macro avg       0.73      0.68      0.70      4957
weighted avg       0.88      0.89      0.88      4957

Confusion Matrix  [[  73  188   29]
 [  74 3642  116]
 [  16  114  705]]
Macro Average F1 Score  0.6986064843422541
Weighted Average F1 Score  0.8839485634757537


### since F1 score for class 0 is low we shold try with Char_tfidf

In [ ]:
X_train_tfidf_char=char_tfidf.fit_transform(X_train)
X_test_tfidf_char=char_tfidf.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
model_lr_char=LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    solver='lbfgs',
    n_jobs=-1
)
model_lr_char.fit(X_train_tfidf_char,y_train)

/home/sachchida/anaconda3/envs/agentic-ai/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)


LogisticRegression(class_weight='balanced', max_iter=1000, n_jobs=-1)

In [ ]:
y_pred_lr_char=model_lr_char.predict(X_test_tfidf_char)

In [ ]:
print(f"classification_report",classification_report(y_test,y_pred_lr_char))
print(f"Confusion Matrix ",confusion_matrix(y_test,y_pred_lr_char))
print(f"Macro Average F1 Score ",f1_score(y_test,y_pred_lr_char,average="macro"))
print(f"Weighted Average F1 Score ",f1_score(y_test,y_pred_lr_char,average="weighted"))

classification_report               precision    recall  f1-score   support

           0       0.34      0.56      0.42       290
           1       0.97      0.87      0.92      3832
           2       0.75      0.93      0.83       835

    accuracy                           0.86      4957
   macro avg       0.69      0.79      0.72      4957
weighted avg       0.89      0.86      0.87      4957

Confusion Matrix  [[ 161   77   52]
 [ 290 3333  209]
 [  18   37  780]]
Macro Average F1 Score  0.7238613542538347
Weighted Average F1 Score  0.8728401496369034


## somewhat improved try SVC

In [ ]:
svm_char=LinearSVC()
svm_char.fit(X_train_tfidf_char,y_train)
y_pred_svm_char=svm_char.predict(X_test_tfidf_char)

In [ ]:
print(f"classification_report",classification_report(y_test,y_pred_svm_char))
print(f"Confusion Matrix ",confusion_matrix(y_test,y_pred_svm_char))
print(f"Macro Average F1 Score ",f1_score(y_test,y_pred_svm_char,average="macro"))
print(f"Weighted Average F1 Score ",f1_score(y_test,y_pred_svm_char,average="weighted"))

classification_report               precision    recall  f1-score   support

           0       0.52      0.22      0.31       290
           1       0.92      0.96      0.94      3832
           2       0.83      0.84      0.83       835

    accuracy                           0.89      4957
   macro avg       0.75      0.67      0.69      4957
weighted avg       0.88      0.89      0.88      4957

Confusion Matrix  [[  65  192   33]
 [  53 3665  114]
 [   8  129  698]]
Macro Average F1 Score  0.6936774415573342
Weighted Average F1 Score  0.8830495425517101


### LR performing better than SVC will use mix of char+word tfidf

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

word_tfidf = TfidfVectorizer(
    analyzer='word',
    ngram_range=(1, 2),
    min_df=3,
    max_df=0.9,
    stop_words='english'
)

char_tfidf = TfidfVectorizer(
    analyzer='char',
    ngram_range=(3, 5),
    min_df=3
)

In [ ]:
from sklearn.pipeline import FeatureUnion

tfidf_union = FeatureUnion([
    ('word_tfidf', word_tfidf),
    ('char_tfidf', char_tfidf)
])

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([
    ('tfidf', tfidf_union),
    ('clf', LogisticRegression(
        max_iter=1000,
        class_weight='balanced',
        n_jobs=-1
    ))
])


In [ ]:
pipeline.fit(X_train, y_train)
y_pred_pipeline = pipeline.predict(X_test)

/home/sachchida/anaconda3/envs/agentic-ai/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
print(f"classification_report",classification_report(y_test,y_pred_pipeline))
print(f"Confusion Matrix ",confusion_matrix(y_test,y_pred_pipeline))
print(f"Macro Average F1 Score ",f1_score(y_test,y_pred_pipeline,average="macro"))
print(f"Weighted Average F1 Score ",f1_score(y_test,y_pred_pipeline,average="weighted"))

classification_report               precision    recall  f1-score   support

           0       0.36      0.54      0.43       290
           1       0.97      0.89      0.93      3832
           2       0.78      0.93      0.85       835

    accuracy                           0.87      4957
   macro avg       0.70      0.78      0.73      4957
weighted avg       0.90      0.87      0.88      4957

Confusion Matrix  [[ 156   89   45]
 [ 249 3406  177]
 [  26   34  775]]
Macro Average F1 Score  0.7347399757925647
Weighted Average F1 Score  0.8832280613786039


### Using BERT

In [39]:
import re

def clean_for_bert(text):
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'@\w+', '', text)
    return text.strip()

### TFIDF can be replaced by Tokenization

In [40]:
from transformers import BertTokenizer
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")
def tokenize(batch):
    return tokenizer(
        batch['tweet'],
        padding='max_length',
        truncation=True,
        max_length=128
    )

In [41]:
from datasets import Dataset, ClassLabel

dataset = Dataset.from_pandas(
    df[['tweet', 'class']].rename(columns={'class': 'labels'})
)

dataset = dataset.cast_column(
    'labels',
    ClassLabel(num_classes=3, names=['hate', 'offensive', 'neither'])
)

dataset = dataset.train_test_split(
    test_size=0.2,
    stratify_by_column='labels',
    seed=42
)


Casting the dataset:   0%|          | 0/24783 [00:00<?, ? examples/s]

In [42]:
from transformers import BertForSequenceClassification

model = BertForSequenceClassification.from_pretrained(
    'bert-base-uncased',
    num_labels=3
)


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Why are we using class_weights?
| Class | Meaning   | Frequency |
| ----- | --------- | --------- |
| 0     | hate      | ~6% ❌     |
| 1     | offensive | ~75%      |
| 2     | neither   | ~19%      |
Without class weights:

Model learns: “predict offensive most of the time”

Minority class (hate) is ignored

High accuracy, poor macro F1
By default, CrossEntropyLoss is: Loss = −log(P(true_class))
With class weights: Loss = − weight[class] × log(P(true_class)) so we use class_weights = [3.0, 1.0, 1.5]
we manually set loss_fn on the model
loss_fn = CrossEntropyLoss(weight=class_weights)
model.loss_fn = loss_fn

This is same as class weight in logistic regression. LogisticRegression(class_weight='balanced')



In [ ]:
import torch
from torch.nn import CrossEntropyLoss

class_weights = torch.tensor([3.0, 1.0, 1.5]).to('cuda')

loss_fn = CrossEntropyLoss(weight=class_weights)
model.loss_fn = loss_fn


In [34]:
from transformers import Trainer, TrainingArguments
import accelerate
print(accelerate.__version__)

1.12.0


In [ ]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir='./results',
    eval_strategy='epoch',
    save_strategy='epoch',         

    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,

    learning_rate=2e-5,
    weight_decay=0.01,

    logging_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model='macro_f1',
    greater_is_better=True
)


In [45]:
from sklearn.metrics import f1_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = logits.argmax(axis=1)
    return {
        'macro_f1': f1_score(labels, preds, average='macro')
    }


In [46]:
tokenized_dataset = dataset.map(tokenize, batched=True)

tokenized_dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "labels"]
)


Map:   0%|          | 0/19826 [00:00<?, ? examples/s]

Map:   0%|          | 0/4957 [00:00<?, ? examples/s]

In [47]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset['train'],
    eval_dataset=tokenized_dataset['test'],
    compute_metrics=compute_metrics
)

trainer.train()


TrainOutput(global_step=3720, training_loss=0.22862443629131524, metrics={'train_runtime': 140.3636, 'train_samples_per_second': 423.742, 'train_steps_per_second': 26.503, 'total_flos': 3912364964906496.0, 'train_loss': 0.22862443629131524, 'epoch': 3.0})

In [49]:
predictions = trainer.predict(tokenized_dataset["test"])


In [50]:
import numpy as np

y_true = predictions.label_ids
y_pred = np.argmax(predictions.predictions, axis=1)


In [52]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_true,
        y_pred,
        target_names=["hate", "offensive", "neither"]
    )
)
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)
print(cm)
from sklearn.metrics import f1_score

macro_f1 = f1_score(y_true, y_pred, average="macro")
weighted_f1 = f1_score(y_true, y_pred, average="weighted")

print("Macro F1:", macro_f1)
print("Weighted F1:", weighted_f1)



              precision    recall  f1-score   support

        hate       0.52      0.41      0.46       286
   offensive       0.94      0.96      0.95      3838
     neither       0.90      0.89      0.90       833

    accuracy                           0.92      4957
   macro avg       0.79      0.75      0.77      4957
weighted avg       0.91      0.92      0.91      4957

[[ 118  155   13]
 [  92 3678   68]
 [  16   73  744]]
Macro F1: 0.7694336739059638
Weighted F1: 0.9128750261663721


### Lets improve this further by using class_weights [4.0, 1.0, 1.5]

In [53]:
model = BertForSequenceClassification.from_pretrained(
    'bert-base-uncased',
    num_labels=3
)
class_weights = torch.tensor([4.0, 1.0, 1.5]).to('cuda')

loss_fn = CrossEntropyLoss(weight=class_weights)
model.loss_fn = loss_fn

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [54]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir='/home/sachchida/gitrepo/ml/data/results',
    eval_strategy='epoch',
    save_strategy='epoch',         

    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=5, ## increased epoch from 3->5

    learning_rate=2e-5,
    weight_decay=0.01,

    logging_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model='macro_f1',
    greater_is_better=True
)


In [55]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset['train'],
    eval_dataset=tokenized_dataset['test'],
    compute_metrics=compute_metrics
)

trainer.train()

TrainOutput(global_step=6200, training_loss=0.17713995656659526, metrics={'train_runtime': 232.0811, 'train_samples_per_second': 427.135, 'train_steps_per_second': 26.715, 'total_flos': 6520608274844160.0, 'train_loss': 0.17713995656659526, 'epoch': 5.0})

In [56]:
predictions = trainer.predict(tokenized_dataset["test"])
import numpy as np

y_true = predictions.label_ids
y_pred = np.argmax(predictions.predictions, axis=1)

In [57]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_true,
        y_pred,
        target_names=["hate", "offensive", "neither"]
    )
)
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)
print(cm)
from sklearn.metrics import f1_score

macro_f1 = f1_score(y_true, y_pred, average="macro")
weighted_f1 = f1_score(y_true, y_pred, average="weighted")

print("Macro F1:", macro_f1)
print("Weighted F1:", weighted_f1)



              precision    recall  f1-score   support

        hate       0.53      0.40      0.46       286
   offensive       0.94      0.96      0.95      3838
     neither       0.90      0.88      0.89       833

    accuracy                           0.91      4957
   macro avg       0.79      0.75      0.76      4957
weighted avg       0.91      0.91      0.91      4957

[[ 114  160   12]
 [  85 3686   67]
 [  15   87  731]]
Macro F1: 0.7648303077291674
Weighted F1: 0.9103465776618838
